name: buildandpush

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'uarenforecasting/advi'
    steps:
      - uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: harbor.x.energy.arizona.edu/library/advi
          tags: |
            type=semver, pattern={{version}}
            type=ref, event=branch
            type=ref, event=tag
            type=sha

      - name: Log in to registry
        uses: docker/login-action@v1
        with:
          registry: harbor.x.energy.arizona.edu
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        id: build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Trigger deployment
        run: |
          REF=$(echo ${GITHUB_SHA} | cut -c -8)
          DATA='{"ref":"master","inputs":{"name":"'${NAME}'","digest":"'${DIGEST}'","ref":"'${REF}'"}}'
          echo ${DATA}
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -u ${USERNAME}:${PASSWORD} \
          https://api.github.com/repos/uarenforecasting/fx-deploy/actions/workflows/update-image.yml/dispatches \
          -d ${DATA}
        env:
          NAME: advi
          DIGEST: ${{ steps.build.outputs.digest }}
          USERNAME: ${{ secrets.DEPLOY_USERNAME }}
          PASSWORD: ${{ secrets.DEPLOY_TOKEN }}
